using IronPlus.Interfaces;
using System.Collections.Generic;

namespace IronPlus.ViewModels
{
    public class HowToUseWarmUpCalculationViewModel : BaseViewModel
    {
        public HowToUseWarmUpCalculationViewModel(IDialogService dialogService, ISettingsService settingsService) : base(dialogService, settingsService)
        {
            Title = "How To Use";

            GenerateWarmUpWeightsLabel = "How to generate new warm up weights:";

            GenerateWarmUpWeightsSteps = new List<string> { "Input the weight you are working up to.", "Select either pounds or kilograms.", "Select if you're using a competition collar.", "Select your barbell (if you have custom barbells)" };

            AutoGeneratedLabel = "New warm up weights are generated every time an input is changed.";

            SpecificWeightLabel = "Tap a specific warm up weight to see a loaded barbell.";
        }

        string generateWarmUpWeightsLabel;
        public string GenerateWarmUpWeightsLabel
        {
            get => generateWarmUpWeightsLabel;
            set => SetProperty(ref generateWarmUpWeightsLabel, value);
        }

        List<string> generateWarmUpWeightsSteps;
        public List<string> GenerateWarmUpWeightsSteps
        {
            get => generateWarmUpWeightsSteps;
            set => SetProperty(ref generateWarmUpWeightsSteps, value);
        }

        string lastWarmUpLabel;
        public string LastWarmUpLabel
        {
            get => lastWarmUpLabel;
            set => SetProperty(ref lastWarmUpLabel, value);
        }

        string specificWeightLabel;
        public string SpecificWeightLabel
        {
            get => specificWeightLabel;
            set => SetProperty(ref specificWeightLabel, value);
        }

        string autoGeneratedLabel;
        public string AutoGeneratedLabel
        {
            get => autoGeneratedLabel;
            set => SetProperty(ref autoGeneratedLabel, value);
        }
    }
}
