using IronPlus.Interfaces;
using System.Collections.Generic;

namespace IronPlus.ViewModels
{
    public class HowToUseUnitConversionViewModel : BaseViewModel
    {
        public HowToUseUnitConversionViewModel(IDialogService dialogService, ISettingsService settingsService) : base(dialogService, settingsService)
        {
            Title = "How To Use";

            GenerateNewConversionLabel = "How to generate a new conversion:";
            GenerateNewConversionSteps = new List<string> { "Input a weight (between 20-501 for kilograms and between 45-1104 for pounds).", "Select a conversion type.", "Select if you are using a competition collar.", "If you are using a custom barbell, select the type of barbell that your are using." };

            AutoGeneratedLabel = "A new barbell is loaded every time an input is changed.";

            AddCustomBarbellLabel = "How to add/edit a custom barbell:";
            AddCustomBarbellSteps = new List<string> { "Go to Settings > Barbells" };

            ChangeRoundSettingLabel = "You can change what value the load rounds to in the Settings tab.";
        }

        string generateNewConversionLabel;
        public string GenerateNewConversionLabel
        {
            get => generateNewConversionLabel;
            set => SetProperty(ref generateNewConversionLabel, value);
        }

        List<string> generateNewConversionSteps;
        public List<string> GenerateNewConversionSteps
        {
            get => generateNewConversionSteps;
            set => SetProperty(ref generateNewConversionSteps, value);
        }

        string addCustomBarbellLabel;
        public string AddCustomBarbellLabel
        {
            get => addCustomBarbellLabel;
            set => SetProperty(ref addCustomBarbellLabel, value);
        }

        List<string> addCustomBarbellSteps;
        public List<string> AddCustomBarbellSteps
        {
            get => addCustomBarbellSteps;
            set => SetProperty(ref addCustomBarbellSteps, value);
        }

        string changeRoundSettingLabel;
        public string ChangeRoundSettingLabel
        {
            get => changeRoundSettingLabel;
            set => SetProperty(ref changeRoundSettingLabel, value);
        }

        string autoGeneratedLabel;
        public string AutoGeneratedLabel
        {
            get => autoGeneratedLabel;
            set => SetProperty(ref autoGeneratedLabel, value);
        }
    }
}
